-- CREATE USER zagoga IDENTIFIED BY 1234;
-- GRANT CONNECT,RESOURCE,UNLIMITED TABLESPACE, CREATE VIEW, CREATE TRIGGER TO zagoga;

-- 1. 유저
CREATE TABLE USERS (
    U_NO NUMBER PRIMARY KEY,
    U_NAME VARCHAR2(20),
    U_NICK VARCHAR2(40),
    U_MAIL CLOB, /*= id*/
    U_PWD VARCHAR2(20),
    U_GENDER VARCHAR2(5),
    U_JUMIN VARCHAR2(13),
    -- 로케이션
    U_PHONE VARCHAR2(13),
    U_JOIN TIMESTAMP DEFAULT SYSDATE,
    -- 결재 방식은 좀 더 생각해보기..

    CONSTRAINT GENDER_CK CHECK (U_GENDER IN ('남', '여'))
);
-- auto increase 생성해야 함 (시퀀스)
CREATE SEQUENCE AUTO_UNO START WITH 1 INCREMENT BY 1 NOMAXVALUE;

-- 2. 사업자
CREATE TABLE HOST (
    H_NO NUMBER PRIMARY KEY,
    H_BIZNO VARCHAR2(12) NOT NULL,
    H_NAME VARCHAR2(20),
    H_JUMIN VARCHAR2(13),
    H_EMAIL CLOB NOT NULL,
    H_PWD VARCHAR2(20) NOT NULL,
    H_PHONE VARCHAR2(13),
    H_BANK CLOB,
    H_JOIN TIMESTAMP DEFAULT SYSDATE
);
-- auto increase (시퀀스)
CREATE SEQUENCE AUTO_HNO START WITH 1 INCREMENT BY 1 NOMAXVALUE;

-- 3. 게스트 하우스 본체
CREATE TABLE GHOUSE (
    GH_NO NUMBER PRIMARY KEY,
    GH_NAME CLOB,
    GH_IMAGE CLOB,
    GH_ADDR1 CLOB,
    GH_ADDR2 CLOB,
    GH_DETAIL CLOB,

    GH_HNO NUMBER NOT NULL,
    FOREIGN KEY (GH_HNO) REFERENCES HOST(H_NO)
);
-- auto increase
CREATE SEQUENCE AUTO_GHNO START WITH 1 INCREMENT BY 1 NOMAXVALUE;

-- 3. 방(숙소정보) only 게스트 하우스
CREATE TABLE ROOMS (
    R_NO NUMBER PRIMARY KEY,
    R_NAME CLOB,
    R_PMIN NUMBER(2), -- 최소 수용 인원
    R_PMAX NUMBER(2), -- 최대 수용 인원
    -- 인원 = 침대갯수
    R_FEE NUMBER,
    R_DETAIL CLOB,

    R_GHNO NUMBER NOT NULL,
    FOREIGN KEY (R_GHNO) REFERENCES GHOUSE(GH_NO)
);
-- auto increase
CREATE SEQUENCE AUTO_RNO START WITH 1 INCREMENT BY 1 NOMAXVALUE;

-- 4. 예약
CREATE TABLE BOOKING (
    B_NO NUMBER PRIMARY KEY,
    B_IN TIMESTAMP,
    B_OUT TIMESTAMP,
    B_STATE NUMBER(1), -- 0: 고려중 , 1: 승낙, 2: 거절
    B_PNO NUMBER(2),
    B_JOIN TIMESTAMP DEFAULT SYSDATE,

    B_RNO NUMBER NOT NULL,
    B_UNO NUMBER NOT NULL,

    CONSTRAINT STATE_CK CHECK (B_STATE IN (0, 1, 2)),
    FOREIGN KEY (B_UNO) REFERENCES USERS(U_NO),
    FOREIGN KEY (B_RNO) REFERENCES ROOMS(R_NO)
);
-- auto increase
CREATE SEQUENCE AUTO_BNO START WITH 1 INCREMENT BY 1 NOMAXVALUE;

-- 5. 이미지
CREATE TABLE IMAGES (
    I_NO NUMBER PRIMARY KEY,
    I_NAME CLOB,
    I_PATH CLOB,
    I_RNO NUMBER,

    FOREIGN KEY (I_RNO) REFERENCES ROOMS(R_NO)
);
-- auto increase
CREATE SEQUENCE AUTO_INO START WITH 1 INCREMENT BY 1 NOMAXVALUE;

-- 6. 관리자
CREATE TABLE ADMINS (
  A_NO NUMBER PRIMARY KEY,
  A_ID VARCHAR2(10),
  A_PWD VARCHAR2(20)
);
-- auto increase
CREATE SEQUENCE AUTO_ANO START WITH 1 INCREMENT BY 1 NOMAXVALUE;

-- 7. 댓글 ( 게스트 하우스에 댓글 달기 )
CREATE TABLE REVIEWS (
  RV_NO NUMBER NOT NULL,
  RV_CONTENT CLOB,
  RV_STAR NUMBER(1),
  RV_UNO NUMBER,
  RV_GHNO NUMBER,
  RV_JOIN TIMESTAMP DEFAULT SYSDATE,

  CONSTRAINT STAR_CK CHECK (RV_STAR BETWEEN 0 AND 5),
  FOREIGN KEY (RV_UNO) REFERENCES USERS(U_NO),
  FOREIGN KEY (RV_GHNO) REFERENCES GHOUSE(GH_NO)
);
-- auto increase
CREATE SEQUENCE AUTO_RVNO START WITH 1 INCREMENT BY 1 NOMAXVALUE;